
environment:
  matrix:
    - PYTHON: "C:\\Python27"
    
install:
  - "%PYTHON%\\python.exe -m pip install pipenv pytest pytest-mock tox codecov"

build: off

test_script:
  - "%PYTHON%\\python.exe -m tox"

on_success:
  - codecov -t "f724c10c-2237-44b6-91af-1de44fe33bfd"
