
environment:
  CODECOV_TOKEN: "f724c10c-2237-44b6-91af-1de44fe33bfd"
  matrix:
    - PYTHON: "C:\\Python27-x64"

install:
  - "%PYTHON%\\python.exe -m pip install tox codecov"

build: off

test_script:
  - "%PYTHON%\\python.exe -m tox"

on_success:
  - "%PYTHON%\\python.exe -m codecov -t %CODECOV_TOKEN% --file coverage.xml"
